### PR TITLE
fix metrics type name

### PR DESCRIPTION
**Pull request by chinaboard**

### CODE REVIEW

**Comment by chinaboard** [comment]
or use prometheus_client less than 0.3.1
prometheus_client 0.4.0 add
https://github.com/prometheus/client_python/blob/428cf1b66937918cf303a441ee8c6ee5441d2a5d/prometheus_client/exposition.py#L93
```
        if mtype == 'counter':
            mname = mname + '_total'
        elif mtype == 'info':
            mname = mname + '_info'
            mtype = 'gauge'
        elif mtype == 'stateset':
            mtype = 'gauge'
        elif mtype == 'gaugehistogram':
            # A gauge histogram is really a gauge,
            # but this captures the strucutre better.
            mtype = 'histogram'
        elif mtype == 'unknown':
            mtype = 'untyped'
```

**Comment by chinaboard** [comment]
@ewiseblatt

**Comment by ewiseblatt** [comment]
Thanks for bringing this to my attention. This munging in their client library is unfortunate, but I think this is the wrong response. I think we should be more explicit about the names we use, especially when we are already munging the name for the timers.

Could you instead change "normalize_name_and_tags()":
    https://github.com/spinnaker/spinnaker-monitoring/blob/master/spinnaker-monitoring-daemon/spinnaker-monitoring/spectator_client.py#L253

(1) So that it takes a kwarg "openmetrics_policy=False"
       * If the policy is True then force the names to have a '_total' on the end there.
       * Instead of taking the statistic tag as is, make a map with something like:
              {'count': 'count_total', 'totalTime': 'time_total', 'totalAmount': 'amount_total'}
      * If you didnt find a statistic tag, then add "_total" if
            determine_primitive_kind(metric_metadata['kind']) == COUNTER_PRIMITIVE_KIND.
(2) Have prometheus client call it with openmetrics_policy=True
(3) Change the dashboards to the new names.
      * In your original proposal you only seem to have the the timers, but it looks like all counters
         should have been affected


This will be more explicit and available to apply the policy to other metric stores.

**Comment by ewiseblatt** [comment]
You'll probably need to update the prometheus unit tests as well. Maybe the spectator_client unit tests for the normalize_name_and_tags function to test when the policy is true.

**Comment by ewiseblatt** [comment]
Hold off for a bit on my suggestion. I am making some inquiries about OpenMetrics which might affect my response.

**Comment by ewiseblatt** [comment]
FYI I just sent this out: https://github.com/spinnaker/spinnaker-monitoring/pull/112

It doesnt address this directly, but changes the interface to using the normalize_name_and_tags. If that goes in, I would add the OpenMetrics policy configuration to the SpectatorClientHelper constructor I added, change the function based on that configuration, and have prometheus force that option on when constructing its Helper instance.

I'm awaiting feedback on that PR so still hold off a little longer to avoid merge conflicts or other implementation changes.

**Comment by ewiseblatt** [comment]
You could also force a version, but it doesnt change any of the above suggestions. The names should still be fixed. Why have metrics called "x_totalTime_total"? I'd prefer being explicit about the names that are going to be exported; it seems like bad practice to rely on a lower level external library to munge the names so that they are consistent with other queries at the same level of abstraction in other tools. If they were just internal it would not matter.

Really the client library should be be munging the names. Offhand that seems like a horrible decision to me.

**Pull request closed without merging**
