### PR TITLE
fix(datadog): Use configparser to read datadog config file

### PR DESCRIPTION
**Pull request by okoye**
The current regex expression that extracts api keys from the datadog
config file does not work well. As python config parser supports the
config file format, it is better to leverage it directly

@lwander @ewiseblatt PTAL

### CODE REVIEW

**Comment by ewiseblatt** [comment]
LGTM, but fix the failing datadog test.

**Comment by okoye** [comment]
@ewiseblatt thanks for the review! I've updated the tests.

**Comment by okoye** [comment]
FYI @spinnaker/reviewers.

**Comment by ewiseblatt** [comment]
sorry I lost this after your response. i cant check it now but will later today.

**Comment by ewiseblatt** [comment]
thanks for doing this.

**Pull request merged**
