### PR TITLE
fix(prometheus): Dont use '-' in metric names

### PR DESCRIPTION
**Pull request by ewiseblatt**

### CODE REVIEW

**Comment by kskewes** [comment]
Related issue: https://github.com/spinnaker/spinnaker/issues/3578
Doing the replace against the complete `metric_name` like you have is safer than just applying to `service`.

On another side note.
Tend to see underscores in Prometheus metric names more than colons. Prometheus project does underscores for its metrics.
I can do a PR for updating the supplied dashboards but changing separator from `:` to `_` would break a lot of peoples existing dashboards, probably not worth it?

**Comment by ewiseblatt** [comment]
I'm trying to clean up some configuration. You can add an option to control how prometheus does the subtitution and default it to the old behavior. Then you wont break anyone that doesnt want to be broken and support people that want the right thing.

I thought ":" was used for hierarchy. Looking at prometheus docs now, I dont notice any naming standard syntax and the use of special characters. Is there a standard?

I will be introducing a different naming scheme which when opted-in is going to break everyone but will offer more control and a chance to normalize/standardize across metrics. There I use "/" as hierarchy separators (which is why I am replacing '/' with ':') and intend to use '_' as snake-case. No '.'. You might want to hold off until you see that.

I was hoping to initiate public discussion this week but other things came up before I could put together a PR and doc to discuss. I'm trying to get the implementation mechanisms in so people can play with it to comment on it before going too far down that path.

**Comment by ewiseblatt** [comment]
> Doing the replace against the complete metric_name like you have is safer than just applying to service
Absolutely. However I see the problems as being separate, and I think you pointed out that the HA services dont work with the sample dashboards. The service normalization is an option to sidestep these issues. Should you choose not to then this mechanism would kick in as a fallback. Plus it would hold for other metrics should a "-" get introduced somewhere.

This is still needed because one might want to distinguish the different service variants. Longer term there will be another tag for doing that, but that isnt in yet nor would be be patchable into existing releases.

**Comment by kskewes** [comment]
Prometheus data model:
https://prometheus.io/docs/concepts/data_model/
Open Metrics draft?: https://github.com/OpenObservability/OpenMetrics/blob/master/markdown/metric_exposition_format.md

**Comment by ewiseblatt** [comment]
thanks for the links. Hold on here. I'm going to add the feature flag in with this change while we're talking about it.

**Comment by ewiseblatt** [comment]
Actually I am going to do that change in anotehr PR.

**Pull request merged**
